# Generated by Django 3.1 on 2020-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='Author Name', max_length=80),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_required',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Recipe', max_length=50),
        ),
    ]
